### ISSUE TITLE
[Parsing] Extract level of data from resource name

### ISSUE THREAD

**Issue by nightsh** [CivicActions/edscrapers#104]
Some datasets have resources named the same as U.S. states etc. We can use this as a heuristic to determine the level of data, in some cases.

Tasks:

- [x] identify what are the patterns
- [x] create a map of what file name mean what level of data
- [x] implement it in either parsers or transformers
- [x] import/adopt the 'enhancement' from the transformer into the data.son

Acceptance criteria:

- [x] datasets having state level files named the same as the states will have the appropriate level of data
- [x] 'enhancement' is adopted by data.json/harvester and is visible on the data portal

**Comment by osahon-okungbowa** [comment]
This issue is handled by the `sanitize` transformer

**Comment by osahon-okungbowa** [comment]
sanitisation has been adopted into data.json, so this issue can be closed
